language: objective-c
before_install:
  - gem install xcpretty
script:
  - xcodebuild -project BlockValueTransformer.xcodeproj -scheme BlockValueTransformerTests  -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' test | xcpretty -c
